### ISSUE TITLE
Npm module

### ISSUE THREAD

**Issue by amilajack** [duanyao/codecbox.js#2]
It would be nice if an npm module could be provided for this repo.

**Comment by amilajack** [comment]
I can make the PR for this if its alright with you and you can publish it.

**Comment by duanyao** [comment]
Sure, thanks! I thought most people would like a custom build to reduce the size. If you think the default build is OK for you, fine!

**Comment by amilajack** [comment]
Actually custom builds would be better now that I think about it.
